import { Footer } from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "@/components/Header";

const mainFont = Roboto({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "My Blog",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Header />
        <main className="container mx-auto mt-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
